### ISSUE TITLE
bcf: viewer labels topics as "issues", contradicting the BCF specification and the rest of the codebase

### ISSUE THREAD

**Issue by BIMvoice** [louistrue/ifc-lite#4096]
The viewer labels the BCF panel **"BCF issues"**, but everything else in the codebase — and the buildingSMART specification — calls these **topics**. "Issue" is one *value* of `TopicType`, not the name of the container.

## What the specification says

From the [BCF-XML documentation](https://github.com/buildingSMART/BCF-XML/blob/release_2_1/Documentation/README.md):

- **`Topic` is the element.** "Topic node contains reference information of the topic. It has one required attribute, which is the topic GUID (`Guid`)." Each Markup has exactly one Topic.
- **`TopicType` is an attribute of it**, "Predefined list in `extensions.xml`".
- buildingSMART's own description of scope: "Each Markup has a Topic that can relate to anything from **issues** in the design, clashes, design proposals, change requests, or quality assurance failures."

So "issue" is a *kind* of topic. Our own `TOPIC_TYPES` already encodes this correctly:

```ts
export const TOPIC_TYPES = ['Issue', 'Request', 'Comment', 'Error', 'Warning', 'Info'];
```

Calling the collection "issues" therefore both contradicts the spec and narrows it — a clash, a request or an Info topic is not an issue. It also reads oddly next to a topic whose `TopicType` is `Request`.

## Where the code disagrees with itself

User-facing:

- `apps/viewer/src/lib/panels/registry.ts` — the panel entry's `title: 'BCF issues'` (the sidebar icon tooltip)
- `apps/viewer/src/components/viewer/BCFPanel.tsx` — the panel heading `<h2>BCF Issues</h2>`
- `BCFPanel.tsx` — default export filenames `BCF_Issues_<date>` and `<model>_Issues`, plus the `sanitizeFilename` fallback `'issues'`
- `bcf/BCFCreateTopicForm.tsx` — placeholder "Brief description of the issue"
- `bcf/BCFTopicList.tsx` — "Set your email to identify your issues and comments"

Everything else already uses Topic consistently: `BCFCreateTopicForm`, `BCFTopicList`, `bcfHeaderFiles.ts`, the `packages/bcf` reader/writer, and the anchor comment in `lib/tours/anchors.ts` ("disabled until a topic exists").

`TOPIC_TYPES` should **not** change — `'Issue'` is a legitimate value there and matches the spec.

## Proposed change

Rename the user-facing container language from "issues" to "topics" in the five places above. Component names, props and state are already correct and need no churn.

One judgement call worth flagging rather than deciding silently: the **default export filename** would change from `<model>_Issues.bcfzip` to `<model>_Topics.bcfzip`. That is only a default — the user can edit it, and it does not affect archive contents or interoperability — but it is the most visible part of the change and could surprise anyone with tooling that keys off the name. Happy to leave the filename alone and change only the labels if you would prefer the smaller blast radius.

Reported by @petrucond after noticing the panel icon said "issues" while the UI it opens talks about topics.

**Comment by BIMvoice** [comment]
Consolidated state after today's merge wave, since several constraints interact and are easy to reconstruct wrongly. Everything below was executed rather than inferred — I got two "PR X clears PR Y" claims wrong earlier today by reasoning instead of running, so each claim here names what was run.

## `main` is currently red on two independent ratchets

```
module_size_ratchet          rust/geometry/src/processors/boolean/mod.rs   948 > 936
check-server-browser-type-parity   4 stale ALLOWLIST entries
```

Both are inherited by every PR that rebases, which is why #4102, #4090, #4089 and #4018 show red for reasons unrelated to their own changes.

**#4101 fixes both.** It carries the `boolean/mod.rs` split (948 → 920) *and* the parity prune. Verified by running the gate on its head `849846577`: `module_size_ratchet` `6 passed; 0 failed`, and a full 59-entry allowlist scan showing 0 over budget.

The parity failure is the new staleness detector from #3979 working correctly, not a bug. #3979 merged at 13:31; #3971 and #3973 merged seconds later and closed the divergences those four entries muted. Their notes still read `open PR #3973` and `open PR #3971`. Each was re-verified as genuinely closed on both sides before removal — `is_spatial_type` now matches `IFCSPATIALZONE`/`IFCMARINEPART`/`IFCFACILITYPARTCOMMON`, and `properties.rs` now has an `IFCCOMPLEXPROPERTY` arm.

## The one trap worth knowing about

**#4101 and #4089 cannot both be auto-merged.** Each extracts the same `impl GeometryProcessor for BooleanClippingProcessor` out of `mod.rs`, to different files — `router_impl.rs` and `failures.rs` respectively. After resolving one small `mod.rs` hunk the tree looks clean and `git merge-tree` reports no conflict, then:

```
error[E0119]: conflicting implementations of trait `GeometryProcessor`
              for type `BooleanClippingProcessor`
```

Whichever lands second needs a manual resolution: delete one impl block. #4089's copy is the strict superset (it has `bool_failure_count` and `truncate_bool_failures_to` from #4083), so keeping that one loses nothing.

Both independently clear the ratchet — #4101 at 920 lines, #4089 at 925, both under 936, both `6 passed`. They are alternatives for that purpose, not a pair.

## Suggested order

1. **#4101** — clears both red gates in one move.
2. **#4089** — resolve the E0119 duplicate impl by hand; do not trust the clean-looking merge.
3. **#4105** — redundant if #4101 lands (parity prune only). Close unless you want the two fixes separated.
4. **#4090** — rebased, `e892bc637`, MERGEABLE. Its dispatcher went 631 → 565 by extraction after merging #4079; no budget raised.
5. **#4102** — CI Python provisioning. Note it does **not** by itself clear #4048, contrary to what I said earlier today.
6. **#4040** — retarget onto `main` first. #3973 has merged, so this is now possible; until then its green means "never ran", not "passed".
7. **#4024** — its logic is redundant with #3922 (merged 13:31); `mod.rs` is byte-identical to main. Only its synthetic bowtie test is unique.

## Corrections to earlier claims of mine

- **#4090 does not clear #4024.** Running #4090's own oracle against #4024 gives `BASELINE-BROKEN`, not `OBSERVED`: enabling `csg_topology_gate` compiles a fixture-dependent census test that panics with "no fixtures on disk", because the `revert-oracle` job checks out `lfs: false` and never fetches fixtures.
- **#4079 does not clear #4048.** Same shape — the job installs no pytest. #4102 fixes that half; the fixture half is still open.
- **#4048's current verdict is `UNOBSERVED`, not `BASELINE-BROKEN`** — and that run is a full day old, predating today's merges, so neither reading is trustworthy until it re-runs.

The common cause behind the first two: **the `revert-oracle` job runs a deliberately minimal environment, so any change that widens what it executes trips a missing prerequisite.** Worth deciding whether one change should provision both lanes (pytest and fixtures) rather than fixing them separately.

## Still open, needing a decision rather than code

- `CLAUDE_CODE_OAUTH_TOKEN` is unset repo-wide, failing `Claude review` and downstream `Review posted` on every PR.
- #4098 (large single IFC files hit browser memory ceilings while larger federated projects load), #4099 (users asking for a free BCF viewer without knowing ifc-lite is one), #4104 (a `.py` test under `rust/python` is claimed by cargo and fails on an excluded workspace member), #4095 (server and browser disagree on a cross-linked space's parent storey).

**Comment by BIMvoice** [comment]
Apologies — the comment above landed on the wrong thread. It is a board-wide merge summary and has nothing to do with BCF terminology; I meant it for the PR discussion around #4101. Leaving it rather than deleting since the content is accurate and you may find it useful, but please read it as general coordination, not as anything about this issue.

This issue remains just what it says: the viewer labels BCF topics as "issues", contradicting the spec and the rest of the codebase. #4097 implements the rename and is open.
